# -*- ruby -*-
require_relative "lib/gaudi/version"
require "rubygems"
require "hoe"

Hoe.spec "gaudi" do |prj|
  prj.developer("Vassilis Rizopoulos", "vassilisrizopoulos@gmail.com")
  prj.license "MIT"
  prj.version = Gaudi::Gem::Version::STRING
  prj.summary = "Scaffolding and version management for Gaudi"
  prj.urls = { "home" => "http://github.com/damphyr/gaudi" }
  prj.description = prj.paragraphs_of("README.md", 1..5).join("\n\n")
  prj.local_rdoc_dir = "doc/rdoc"
  prj.readme_file = "README.md"
  prj.extra_deps << ["minitar", "~>0.6.1"]
  prj.spec_extras = { :executables => ["gaudi"] }
end

# vim: syntax=ruby
