# -*- ruby -*-
require_relative 'lib/gaudi/version'
require "rubygems"
require "hoe"

# Hoe.plugin :compiler
# Hoe.plugin :gem_prelude_sucks
# Hoe.plugin :inline
# Hoe.plugin :racc
# Hoe.plugin :rcov

Hoe.spec "gaudi" do |prj|
  developer("Vassilis Rizopoulos", "vassilisrizopoulos@gmail.com")
  license "MIT"
  prj.version = Gaudi::Gem::Version::STRING
  prj.summary='Scaffolding and version management for Gaudi'
  prj.urls=["http://github.com/damphyr/gaudi"]
  prj.description=prj.paragraphs_of('README.txt',1..5).join("\n\n")
  prj.local_rdoc_dir='doc/rdoc'
  prj.readme_file="README.txt"
  prj.extra_deps<<["minitar","~>0.6.1"]
  prj.spec_extras={:executables=>["gaudi"],:default_executable=>"gaudi"}
end

# vim: syntax=ruby
